name: dart_algorithm_example
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: ^3.6.0
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.7.0

dev_dependencies:
  test: ^1.22.0
  pedantic: ^1.9.0
